spring.application.name=orderservice
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/orderdb
spring.datasource.username=rohit
spring.datasource.password=rohit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


