spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=rohit
spring.datasource.password=rohit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true